version: '3.7'

services:
  sla-summary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sla-summary
    restart: always
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - node_modules:/usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    networks:
      - sla-summary-network

networks:
  sla-summary-network:

volumes:
  node_modules:
  sla-summary-volume: