version: '3.7'

services:
  sla-summary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sla-summary
    restart: always
    volumes:
      - ./src:/app/src
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3777:3777
    networks:
      - sla-summary-network

networks:
  sla-summary-network:

volumes:
  node_modules:
  sla-summary-volume: